--     --7
--     DELIMITER / / CREATE FUNCTION sayhello(name char(40)) RETURNS char(100) DETERMINISTIC BEGIN return CONCAT('hello', ' ', name);
-- END / / DELIMITER;
-- --8
-- DELIMITER / / CREATE FUNCTION multiply(x int, y int) RETURNS int DETERMINISTIC BEGIN return x * y;
-- END / / DELIMITER;
-- --9
-- DELIMITER / / CREATE FUNCTION get_score(student_id int, exam_date date) RETURNS int DETERMINISTIC BEGIN declare score int;
-- select
--     score into score
-- from
--     exam_in
-- where
--     student_id = student_id
--     and exam_date = exam_date;
-- return score;
-- --10
-- DELIMITER / / CREATE FUNCTION failed_students(course_code int) RETURNS int DETERMINISTIC BEGIN declare count int;
-- select
--     count(student_id) into count
-- from
--     exam_in
-- where
--     course_code = course_code
--     and score > 50;
-- return count;
-- END / / DELIMITER;
--11
-- DELIMITER // CREATE FUNCTION failed_students(course_code char(40)) RETURNS int DETERMINISTIC BEGIN declare count int;

-- select
--     course_name,
--     avg()
-- select
--     count(student_id) into count
-- from
--     exam_in
-- where
--     course_code = course_code
--     and score > 50;

-- return count;

-- END // DELIMITER;